# Generated by Django 5.0 on 2024-12-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nextcloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='synced_to_nextcloud',
            field=models.BooleanField(default=False),
        ),
    ]
